name: mobx_bmi
description: BMI Calculator with MobX.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.1
  mobx: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2

flutter:
  uses-material-design: true
