name: mobx_bmi
description: App with Examples of MobX in Flutter
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  currency_text_input_formatter: ^2.2.3
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  intl: ^0.19.0
  mobx: ^2.3.3+2
  syncfusion_flutter_gauges: ^26.1.39

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
